"""
Django settings for dashboard_project project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os as _os
import tempfile
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name, default):
    """Read a boolean-ish environment variable."""
    raw = _os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name):
    """Read a comma-separated environment variable into a list of values."""
    return [v.strip() for v in _os.environ.get(name, '').split(',') if v.strip()]


def _env(name, default=''):
    """Read an environment variable, treating an empty one as unset.

    Hosting panels routinely create a variable with a blank value when you add
    the key but do not fill it in. Plain os.environ.get() would then hand back
    '' and silently override the working default below it, which is how a
    deployed copy ends up showing "not configured" where the local one shows
    data. An empty value means "use the default" here.
    """
    return _os.environ.get(name, '').strip() or default


# Render sets RENDER=true inside every service it runs. It lets the settings
# below pick safe production defaults without any extra configuration.
ON_RENDER = 'RENDER' in _os.environ


# SECURITY WARNING: keep the secret key used in production secret!
# Render generates one into DJANGO_SECRET_KEY (see render.yaml); the literal
# fallback exists only so local development works with no setup.
SECRET_KEY = _os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-^^q2jegs0izx*)#_@%!pl)d7(wnl4_c&7c06#lsih%(+-lw!km',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', default=not ON_RENDER)

ALLOWED_HOSTS = ['localhost', '127.0.0.1'] + _env_list('DJANGO_ALLOWED_HOSTS')

# The public hostname Render assigns to the service (e.g. foo.onrender.com).
_render_hostname = _os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if _render_hostname:
    ALLOWED_HOSTS.append(_render_hostname)

if DEBUG and not _env_list('DJANGO_ALLOWED_HOSTS'):
    # Development convenience: accept whatever host it is reached on (a LAN
    # address, the test client, a tunnel). DEBUG is forced off when hosted.
    ALLOWED_HOSTS = ['*']

# Every non-local host is reached over https, and Django needs the origin
# whitelisted for POSTs (the upload and ARTR-build forms) to pass CSRF checks.
CSRF_TRUSTED_ORIGINS = [
    f'https://{host}' for host in ALLOWED_HOSTS
    if host not in ('localhost', '127.0.0.1')
]

if ON_RENDER:
    # TLS is terminated at Render's proxy, which forwards the original scheme.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # HSTS is left off on purpose. It is a hard-to-reverse promise made to the
    # browser for the whole domain, so it should be switched on deliberately
    # once the final domain is settled -- set DJANGO_HSTS_SECONDS to do that.
    SECURE_HSTS_SECONDS = int(_os.environ.get('DJANGO_HSTS_SECONDS', '0'))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves the collected static files in production; must sit directly after
    # SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dashboard_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dashboard_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Point DATABASE_URL at a managed database (e.g. Render Postgres) to use one.
# Without it the sqlite file above is used. That works on Render too, but its
# container filesystem is rebuilt on every deploy and restart, so the sqlite
# file is not durable -- only sessions, messages and admin logins live there,
# and this app defines no models of its own, so losing it costs nothing but a
# re-login to /admin/.
_database_url = _os.environ.get('DATABASE_URL')
if _database_url:
    import dj_database_url

    DATABASES['default'] = dj_database_url.parse(
        _database_url, conn_max_age=600, conn_health_checks=True
    )


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# `collectstatic` gathers everything here during the Render build; WhiteNoise
# serves it from there at runtime.
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        # Compresses and fingerprints the collected files so they can be
        # cached forever by the browser.
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media (uploaded files)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ---------------------------------------------------------------------------
# Google Drive integration (OAuth)
# ---------------------------------------------------------------------------
# Each uploaded Excel file is uploaded into the Drive folder below and
# converted to a Google Sheet there. Uses OAuth user credentials, so the
# created Sheet is owned by the signed-in Google account.
#
# NOTE: keep these secret. Prefer environment variables in real deployments;
# they are read from the environment first, falling back to the values here.
GOOGLE_OAUTH_CLIENT_ID = _env(
    'GOOGLE_OAUTH_CLIENT_ID',
    '805997951734-27vpuhmp5jqvm9ft3skmgq4j2ctj8c0h.apps.googleusercontent.com',
)
# No default on purpose -- a client secret does not belong in the repo. It is
# only needed to run `python manage.py google_auth`; day-to-day the app reads
# the cached token, which already carries the client id and secret inside it.
# Set it in the environment for that one command, or drop it into
# google_credentials.json (git-ignored) next to manage.py.
GOOGLE_OAUTH_CLIENT_SECRET = _env('GOOGLE_OAUTH_CLIENT_SECRET')
# Drive folder id, from the folder URL:
# https://drive.google.com/drive/folders/<THIS_PART>
GOOGLE_DRIVE_FOLDER_ID = _env(
    'GOOGLE_DRIVE_FOLDER_ID',
    '1p5JCjdK1osysVFAaKa9cHnCX6ndruuoy',
)
# Fixed localhost port used by the one-time `google_auth` sign-in flow. The
# port must be fixed (not random) so the redirect URI is stable and can be
# registered in the Cloud Console; a "Web application" OAuth client rejects any
# redirect URI it does not know, with Error 400: redirect_uri_mismatch.
# Register exactly this in Authorized redirect URIs: http://localhost:8080/
GOOGLE_OAUTH_REDIRECT_PORT = int(_os.environ.get('GOOGLE_OAUTH_REDIRECT_PORT', '8080'))

# Where the OAuth refresh token is cached after the one-time sign-in.
GOOGLE_TOKEN_FILE = BASE_DIR / 'google_token.json'

# A hosted deployment cannot use the file above: there is no browser to run the
# sign-in flow in, and the container filesystem does not survive a deploy. So
# sign in once locally and paste the whole contents of google_token.json into
# the GOOGLE_TOKEN_JSON environment variable, which takes precedence over the
# file.  `python manage.py google_token_env` prints exactly what to paste.
GOOGLE_TOKEN_JSON = _env('GOOGLE_TOKEN_JSON')

# Worksheet-title cache (see dashboard/google_drive.py). It must live somewhere
# writable; on Render the project directory is wiped on each deploy anyway, so
# the system temp dir is just as durable and never conflicts with the build.
_default_tab_cache = (
    Path(tempfile.gettempdir()) / 'sheet_tabs_cache.json' if ON_RENDER
    else BASE_DIR / 'sheet_tabs_cache.json'
)
GOOGLE_TAB_CACHE_FILE = Path(
    _os.environ.get('GOOGLE_TAB_CACHE_FILE', _default_tab_cache)
)

# ERP Files page: the Drive folder whose Sheets are listed and viewed.
# Give either the folder id (preferred, unambiguous) OR leave the id blank and
# the app will look the folder up by name.
GOOGLE_ERP_SOURCE_FOLDER_ID = _env(
    'GOOGLE_ERP_SOURCE_FOLDER_ID', '18LIQBhbqxeHlQzvg2AbSttTCu7NjUcsH'
)
GOOGLE_ERP_SOURCE_FOLDER_NAME = _env(
    'GOOGLE_ERP_SOURCE_FOLDER_NAME', 'ERPsourcefile'
)

# Where converted ARTR_Data sheets are saved. Blank => use GOOGLE_DRIVE_FOLDER_ID.
GOOGLE_ARTR_OUTPUT_FOLDER_ID = _env('GOOGLE_ARTR_OUTPUT_FOLDER_ID')

# Final output: the converted Horizontal Cost Sheet (as-is) shown under Output.
GOOGLE_HORIZONTAL_CS_SHEET_ID = _env(
    'GOOGLE_HORIZONTAL_CS_SHEET_ID', '19mGhvUbJTffb8xe9qrV9xiGzXFIhtYUtUyUFyB9s0ZM')

# Converted Sales Dashboard & Reconciliation workbook (as-is).
GOOGLE_SALES_DASHBOARD_SHEET_ID = _env(
    'GOOGLE_SALES_DASHBOARD_SHEET_ID', '1xGpFi0WW-HIFKzL6VShH6EzFDtj8XxXEYyiPbbL5N38')

# --- Costing pipeline (storage = Drive, database = Google Sheets) ---
# Root Drive folder that holds every period's folder tree. Blank => the app
# creates/uses a "Costing" folder in My Drive.
GOOGLE_COSTING_ROOT_FOLDER_ID = _env(
    'GOOGLE_COSTING_ROOT_FOLDER_ID', '16jRbelmg-DCZFVKL4c8V6e9t-CbB5LxX')
# The control spreadsheet used as the application database. Set this from the id
# printed by `python manage.py costing_init`.
GOOGLE_COSTING_DB_SHEET_ID = _env(
    'GOOGLE_COSTING_DB_SHEET_ID', '13y0aI7jnz0JW1Afecb5ck0BbzQZ_ooF1SuD4Ns9EotE')

# Accepted Excel extensions for the ERP upload page.
ALLOWED_EXCEL_EXTENSIONS = ('.xlsx', '.xls')


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
